import type { Metadata } from 'next';
import '@/app/globals.css';
import { Toaster } from '@/components/ui/toaster';
import Providers from '@/components/Providers';
import { authConfig } from '@/app/server/authConfig';
import { getServerSession } from 'next-auth';
import LanguageSwitcher from '@/components/languageSwitcher';

export const metadata: Metadata = {
  title: 'FedChess',
  // description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authConfig);
  const lng = session?.user?.language || 'English';
  const dir = session?.user.isRtl ? 'rtl' : 'ltr';

  return (
    <html lang={lng} dir={dir}>
      <body>
        <Providers lng={lng}>
          {children}
          <LanguageSwitcher lng={lng} />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
