import { FormFieldConfig } from '@/types/form';
import { FieldType, SupportedLanguages } from '@prisma/client';

export const AdminProfileFormConfig: FormFieldConfig[] = [
  {
    id: 'firstNameField',
    fieldName: 'firstName',
    displayName: 'First Name',
    placeholder: 'Enter First Name',
    fieldType: FieldType.TEXT,
    isMandatory: true,
    order: 1,
    validations: {
      minLength: 2,
      maxLength: 50,
    },
    isHidden: false,
    isDisabled: false,
    isCustomField: false,
  },
  {
    id: 'lastNameField',
    fieldName: 'lastName',
    displayName: 'Last Name',
    placeholder: 'Enter Last Name',
    fieldType: FieldType.TEXT,
    isMandatory: true,
    order: 2,
    validations: {
      minLength: 2,
      maxLength: 50,
    },
    isHidden: false,
    isDisabled: false,
    isCustomField: false,
  },
  {
    id: 'passwordField',
    fieldName: 'password',
    displayName: 'Password',
    placeholder: 'Enter New Password',
    fieldType: FieldType.TEXT,
    isMandatory: false,
    order: 3,
    validations: {
      minLength: 8,
    },
    isHidden: false,
    isDisabled: false,
    isCustomField: false,
  },
  {
    id: 'middleNameField',
    fieldName: 'middleName',
    displayName: 'Middle Name',
    placeholder: 'Enter Middle Name',
    fieldType: FieldType.TEXT,
    isMandatory: false,
    order: 4,
    validations: {
      maxLength: 50,
    },
    isHidden: false,
    isDisabled: false,
    isCustomField: false,
  },
  {
    id: 'nameSuffixField',
    fieldName: 'nameSuffix',
    displayName: 'Name Suffix',
    placeholder: 'Enter Name Suffix',
    fieldType: FieldType.TEXT,
    isMandatory: false,
    order: 5,
    validations: {
      maxLength: 10,
    },
    isHidden: false,
    isDisabled: false,
    isCustomField: false,
  },
  {
    id: 'languageField',
    fieldName: 'language',
    displayName: 'Language',
    placeholder: 'Select Language',
    fieldType: FieldType.SELECT,
    isMandatory: true,
    order: 6,
    validations: {
      options: Object.values(SupportedLanguages),
    },
    isHidden: false,
    isDisabled: false,
    isCustomField: false,
  },
];
