export const PERMISSIONS = {
  // Organization permissions
  ORG_VIEW: 'org.view',
  ORG_CREATE: 'org.create',
  ORG_UPDATE: 'org.update',
  ORG_DELETE: 'org.delete',

  // Club permissions
  CLUB_VIEW: 'club.view',
  CLUB_CREATE: 'club.create',
  CLUB_UPDATE: 'club.update',
  CLUB_DELETE: 'club.delete',

  // Event permissions
  EVENT_VIEW: 'event.view',
  EVENT_CREATE: 'event.create',
  EVENT_UPDATE: 'event.update',
  EVENT_DELETE: 'event.delete',

  // Member permissions
  MEMBER_VIEW: 'member.view',
  MEMBER_CREATE: 'member.create',
  MEMBER_UPDATE: 'member.update',
  MEMBER_DELETE: 'member.delete',
} as const;

export const roleMap = {
  SUPER_ADMIN: [
    PERMISSIONS.ORG_VIEW,
    PERMISSIONS.ORG_CREATE,
    PERMISSIONS.ORG_UPDATE,
    PERMISSIONS.ORG_DELETE,
    PERMISSIONS.CLUB_VIEW,
    PERMISSIONS.CLUB_CREATE,
    PERMISSIONS.CLUB_UPDATE,
    PERMISSIONS.CLUB_DELETE,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_DELETE,
  ],
  ORG_ADMIN: [
    PERMISSIONS.CLUB_VIEW,
    PERMISSIONS.CLUB_CREATE,
    PERMISSIONS.CLUB_UPDATE,
    PERMISSIONS.CLUB_DELETE,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_DELETE,
  ],
  CLUB_MANAGER: [
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.EVENT_DELETE,
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_DELETE,
  ],
  MEMBER: [PERMISSIONS.EVENT_VIEW, PERMISSIONS.MEMBER_VIEW],
};
